# Generated by Django 5.2.17 on 2026-09-27 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chore'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chore',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_chores', to=settings.AUTH_USER_MODEL),
        ),
    ]
