# Generated by Django 5.2.17 on 2026-09-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('weekdays', models.CharField(blank=True, default='', max_length=13)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChoreSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_series', to='core.household')),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='core.recurrencerule')),
            ],
        ),
        migrations.AddField(
            model_name='chore',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='core.choreseries'),
        ),
    ]
